image:
  - Visual Studio 2017
  - macos
  - Ubuntu

platform:
  - x64

environment:
  nodejs_version: 12.16.3

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input


install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - npm install -g yarn
  - yarn

build_script:
  - yarn dist
  
artifacts:
  - path: dist\*.exe
  - path: dist\*.dmg

test: off
